.gitignore
README.md
pom.xml

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature
A dependency POM for all powsybl repositories to help developers having consistent dependencies.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them …

Initial version

---

README.md
pom.xml

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature
**What is the current behavior?** *(You can also link to an open issue here)*
1.1.0-SNAPSHOT
1.1.0 and 1.2.0-SNAPSHOT
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them entirely)

Release v1.1.0

---

README.md
pom.xml

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Add network-hypothesis in dependencies (part of the release train)

Add network-hypothesis dependency

---

README.md
pom.xml

**Does this PR already have an issue describing the problem ?**
No
**What kind of change does this PR introduce?** 
Update readme and dependencies version to prepare 1.2.2 release

Prepare 1.2.2 release

---

README.md
pom.xml

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature
**What is the current behavior?** *(You can also link to an open issue here)*
2023.0.0
2023.0.1 with an OLF update
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please …

Prepare release 2023.0.1

---

pom.xml

No
Release
2023.1.0
2023.2.0-SNAPSHOT

Bump 2023.2.0-SNAPSHOT

---

README.md
pom.xml

Feature
Bump powsybl-core to 5.3.1 + update README.md

Bump to powsybl-core 5.3.1 and update README.md

---

pom.xml

Feature
Update dependencies:
- open-loadflow: 1.2.3
- diagram: 3.3.2
- entsoe: 2.5.0

Update OLF 1.2.3, diagram 3.3.2 and entsoe 2.5.0

---

pom.xml

Feature
Update dynawo to 1.14.1

Update dynawo to 1.14.1

---

README.md
pom.xml

No
Feature
2023.3.0-SNAPSHOT
2023.3.0 (first commit) then 2023.4.0-SNAPSHOT (second commit)
**DO NOT** squash the commits

Prepare release v2023.3.0

---

README.md
pom.xml

Feature
Bump powsybl-core to 6.0.1 + update README.md

Bump to powsybl-core 6.0.1 and update README.md

---

README.md
pom.xml

Prepare next release 2023.4.0
2023.4.0-SNAPSHOT version
2023.4.0 and README.md updated (first commit) then 2024.0.0-SNAPSHOT (2nd commit)

Prepare v2023.4.0 release

---

README.md
pom.xml

No
Feature
Powsybl-core is in version 6.1.1
Powsybl-core is in version **6.1.2** (and the `README.md` is updated with upcoming 2023.4.1 version)

Bump powsybl-core to 6.1.2 and update README.md

---

README.md
pom.xml

Prepare next release 2024.0.0
2024.0.0-SNAPSHOT version
2024.0.0 and README.md updated (first commit) then 2024.1.0-SNAPSHOT (2nd commit)

Prepare v2024.0.0 release

---

README.md
pom.xml

No
Feature
Powsybl-core is in version 6.2.0
Powsybl-core is in version **6.2.1** (and the `README.md` is updated with upcoming 2024.0.1 version)

Bump powsybl-core to 6.2.1 and update README.md

---

README.md
pom.xml

No
Feature
Powsybl-core is in version 6.2.1
Powsybl-core is in version **6.2.2** (and the `README.md` is updated with upcoming 2024.0.2 version)

Bump powsybl-core to 6.2.2 and update README.md

---

README.md
pom.xml

No
Feature
- powsybl-core is in version 6.2.2
- powsybl-entsoe in version 2.8.0.
- powsybl-core is in version **6.2.3**
- powsybl-entsoe in version **2.8.1**
(And the `README.md` is updated with upcoming 2024.0.3 version.)

Bump powsybl-core to 6.2.3 and powsybl-entsoe to 2.8.1 + update README.md

---

README.md
pom.xml

Prepare next release 2024.1.0
2024.1.0-SNAPSHOT version
2024.1.0 and README.md updated (first commit) then 2024.2.0-SNAPSHOT (2nd commit)

Prepare v2024.1.0 release

---

README.md
pom.xml

No
- powsybl-core 6.3.1
- powsybl-open-loadflow 1.10.0
- powsybl-core **6.3.2**
- powsybl-open-loadflow **1.11.0**
(and the `README.md` is updated with upcoming 2024.1.2 version)

Bump core to 6.3.2, OLF to 1.11.0 + update README.md

---

README.md
pom.xml

Prepare next release 2024.2.0
2024.2.0-SNAPSHOT version
2024.2.0 and README.md updated (first commit) then 2024.3.0-SNAPSHOT (2nd commit)

Prepare v2024.2.0 release

---

README.md
pom.xml

Prepare next release 2024.3.0
2024.3.0-SNAPSHOT version
2024.3.0 and README.md updated (first commit) then 2024.4.0-SNAPSHOT (2nd commit)

Prepare v2024.3.0 release

---

pom.xml

No
- powsybl-core 6.5.0
- powsybl-open-loadflow 1.13.1
- powsybl-diagram 4.6.1
- powsybl-core **6.5.1**
- powsybl-open-loadflow **1.13.2**
- powsybl-diagram **4.6.2**

Bump core to 6.5.1, OLF to 1.13.2, diagram to 4.6.2

---

pom.xml

No
- powsybl-open-rao 6.1.0
- powsybl-open-rao **6.1.2**

Bump open-rao to 6.1.2

---

README.md
pom.xml

Prepare next release 2024.3.1 on release-v2024.3.0 branch
2024.3.0 version
1. v2024.3.1-SNAPSHOT (first commit)
2. Bump core to 6.5.1, OLF to 1.13.2, diagram to 4.6.2 (#46)
3. Bump open-rao to 6.1.2 (#47)
4. v2024.3.1 + update README.md (last commit)
:warning: Merge on release branch with fast-forward locally, then push, in order to keep the release commit verified

Prepare patch release v2024.3.1

---

README.md

No
Doc update
Last version in README.md is 2024.3.0.
Last version in README.md is **2024.3.1**.

Update README.md: v2024.3.1

---

pom.xml

No
- powsybl-core 6.6.0
- powsybl-dynawo 2.7.0
- powsybl-open-rao 6.2.0
<br/>
- powsybl-core **6.6.1**
- powsybl-dynawo **2.7.1**
- powsybl-open-rao **6.2.1**

Bump core to 6.6.1, dynawo to 2.7.1 and open-rao to 6.2.1

---

README.md

No
Documentation update
Last release in the table is 2024.4.0.
Last release in the table is **2024.4.1** (upcoming version).

Update README.md with version 2024.4.1

---

pom.xml

No
- powsybl-core 6.6.1
- powsybl-open-loadflow 1.14.1
- powsybl-diagram 4.7.0
- powsybl-dynawo 2.7.1
- powsybl-entsoe 2.12.0
- powsybl-open-rao 6.2.1
<br/>
- powsybl-core **6.7.0**
- powsybl-open-loadflow **1.15.0**
- powsybl-diagram **4.8.0**
- powsybl-dynawo **2.8.0**
- powsybl-entsoe **2.13.0**
- powsybl-open-rao **6.4.0**

Bump core to 6.7.0, OLF to 1.15.0, diagram to 4.8.0, dynawo to 2.8.0, entsoe to 2.13.0, open-rao to 6.4.0

---

README.md
pom.xml

Prepare next release 2025.0.0
2025.0.0-SNAPSHOT version
2025.0.0 and README.md updated (first commit) then 2025.1.0-SNAPSHOT (2nd commit)

Bump to v2025.0.0

---

README.md
pom.xml

Prepare next release 2025.0.1 on release-v2025.0.0 branch
2024.5.0 version
1. v2025.0.1-SNAPSHOT (first commit)
2. Bump core to 6.7.1, OLF to 1.15.1 and dynawo to 2.8.1 (#58)
3. v2025.0.1 and README.md update (last commit)
:warning: Merge on release branch with fast-forward locally, then push, in order to keep the release commit verified

Prepare patch release v2025.0.1

---

README.md
pom.xml

Prepare next release 2025.0.2 on release-v2025.0.0 branch
2025.0.1 version
1. v2025.0.2-SNAPSHOT (first commit)
2. #61
3. v2025.0.2 and README.md update (last commit)
:warning: Merge on release branch with fast-forward locally, then push, in order to keep the release commit verified

Prepare patch release v2025.0.2

---

README.md

No
Documentation update
Last release in the table is 2025.0.0.
Last release in the table is **2025.0.2**.

Update README.md with versions 2025.0.1 and 2025.0.2
